export const GalleryData = {
  villaGallery: {
    mandrem: [
      {
        name: "Villa Magnifica",
        images: [
          "/rooms/Magnifica/Magnifica.png",
          "/rooms/Magnifica/magnifica2.webp",
          "/rooms/Magnifica/magnifica6.jpg",
          "/rooms/Magnifica/magnifica12.webp",
          "/rooms/Magnifica/magnifica8.jpg",
          "/rooms/Magnifica/magnifica14.webp",
          "/rooms/Magnifica/magnifica10.webp",
          "/rooms/Magnifica/magnifica11.jpg",
          "/rooms/Magnifica/magnifica18.jpg",
          "/rooms/Magnifica/magnifica19.webp",
          "/rooms/Magnifica/magnifica17.webp",
          "/rooms/Magnifica/magnifica13.webp",
          "/rooms/Magnifica/magnifica4.jpg",
          "/rooms/Magnifica/magnifica1.jpg",
          "/rooms/Magnifica/magnifica5.jpg",
          "/rooms/Magnifica/magnifica9.jpg",
          "/rooms/Magnifica/magnifica15.jpg",
          "/rooms/Magnifica/magnifica16.webp",
          "/rooms/Magnifica/magnifica20.jpg",
          "/rooms/Magnifica/magnifica3.jpg",
          "/rooms/Magnifica/magnifica7.jpg",
        ],
        description:
          "Picture this: Greek-inspired elegance meets tropical bliss, all wrapped up in the heart of Goa.",
      },
      {
        name: "Villa Paradiso",
        images: [
          "/rooms/Paradiso/Paradiso.png",
          "/rooms/Paradiso/paradiso1.jpg",
          "/rooms/Paradiso/paradiso5.jpg",
          "/rooms/Paradiso/paradiso6.webp",
          "/rooms/Paradiso/paradiso10.jpg",
          "/rooms/Paradiso/paradiso11.jpg",
          "/rooms/Paradiso/paradiso12.jpg",
          "/rooms/Paradiso/paradiso15.webp",
          "/rooms/Paradiso/paradiso2.jpg",
          "/rooms/Paradiso/paradiso4.jpg",
          "/rooms/Paradiso/paradiso3.jpg",
          "/rooms/Paradiso/paradiso7.jpg",
          "/rooms/Paradiso/paradiso8.jpg",
          "/rooms/Paradiso/paradiso9.jpg",
          "/rooms/Paradiso/paradiso14.webp",
        ],
        description:
          "Tucked away in the serene landscape of Mandrem, Aroha Palms Paradiso is where luxury meets laid-back Goan charm.",
      },
      {
        name: "Villa Serenity",
        images: [
          "/rooms/Serenity/Serenity.png",
          "/rooms/Serenity/serenity7.jpg",
          "/rooms/Serenity/serenity8.jpg",
          "/rooms/Serenity/serenity9.jpg",
          "/rooms/Serenity/serenity10.jpg",
          "/rooms/Serenity/serenity11.jpg",
          "/rooms/Serenity/serenity13.jpg",
          "/rooms/Serenity/serenity15.jpg",
          "/rooms/Serenity/serenity16.webp",
          "/rooms/Serenity/serenity5.webp",
          "/rooms/Serenity/serenity6.jpg",
          "/rooms/Serenity/serenity14.jpg",
          "/rooms/Serenity/serenity17.webp",
          "/rooms/Serenity/serenity3.webp",
          "/rooms/Serenity/serenity4.jpg",
          "/rooms/Serenity/serenity1.jpg",
        ],
        description:
          "This luxury villa offers a serene and picturesque Greek-inspired setting with elegant whitewashed walls, blue accents, and lush greenery.",
      },
      {
        name: "Villa Caia",
        images: [
          "/rooms/Serenity/serenity8.jpg",
          "/rooms/Serenity/serenity9.jpg",
          "/rooms/Serenity/serenity4.jpg",
          "/rooms/Serenity/serenity1.jpg",
          "/rooms/Emerald/Emerald.png",
          "/rooms/Emerald/emerald1.jpg",
          "/rooms/Emerald/emerald6.webp",
          "/rooms/Emerald/emerald2.jpg",
          "/rooms/Emerald/emerald3.jpg",
          "/rooms/Emerald/emerald4.jpg",
          "/rooms/Emerald/emerald5.webp",
          "/rooms/Regal/Regal.png",
          "/rooms/Regal/regal1.jpg",
          "/rooms/Regal/regal2.jpg",
          "/rooms/Regal/regal3.jpg",
          "/rooms/Regal/regal4.jpg",
          "/rooms/Regal/regal5.jpg",
          "/rooms/Regal/regal6.jpg",
          "/rooms/Regal/regal7.jpg",
          "/rooms/Regal/regal8.jpg",
          "/rooms/Regal/regal9.webp",
        ],
        description:
          "Picture this: Greek-inspired elegance meets tropical bliss, all wrapped up in the heart of Goa. Welcome to Villa Caia.",
      },
      {
        name: "Villa Prana",
        images: [
          "/rooms/Magnifica/Magnifica.png",
          "/rooms/Magnifica/magnifica2.webp",
          "/rooms/Magnifica/magnifica6.jpg",
          "/rooms/Magnifica/magnifica12.webp",
          "/rooms/Magnifica/magnifica8.jpg",
          "/rooms/Magnifica/magnifica14.webp",
          "/rooms/Magnifica/magnifica10.webp",
          "/rooms/Magnifica/magnifica11.jpg",
          "/rooms/Magnifica/magnifica18.jpg",
          "/rooms/Magnifica/magnifica19.webp",
          "/rooms/Paradiso/Paradiso.png",
          "/rooms/Paradiso/paradiso1.jpg",
          "/rooms/Paradiso/paradiso5.jpg",
          "/rooms/Paradiso/paradiso6.webp",
          "/rooms/Paradiso/paradiso10.jpg",
          "/rooms/Paradiso/paradiso11.jpg",
          "/rooms/Paradiso/paradiso12.jpg",
          "/rooms/Paradiso/paradiso15.webp",
          "/rooms/Paradiso/paradiso2.jpg",
          "/rooms/Paradiso/paradiso4.jpg",
        ],
        description:
          "Picture this: Greek-inspired elegance meets tropical bliss, all wrapped up in the heart of Goa. Welcome to Villa Prana.",
      },
      {
        name: "Villa Encanto",
        images: [
          "/rooms/Paradiso/Paradiso.png",
          "/rooms/Paradiso/paradiso1.jpg",
          "/rooms/Paradiso/paradiso5.jpg",
          "/rooms/Paradiso/paradiso6.webp",
          "/rooms/Paradiso/paradiso10.jpg",
          "/rooms/Paradiso/paradiso11.jpg",
          "/rooms/Paradiso/paradiso12.jpg",
          "/rooms/Paradiso/paradiso15.webp",
          "/rooms/Paradiso/paradiso2.jpg",
          "/rooms/Serenity/Serenity.png",
          "/rooms/Serenity/serenity8.jpg",
          "/rooms/Serenity/serenity9.jpg",
          "/rooms/Serenity/serenity4.jpg",
          "/rooms/Serenity/serenity1.jpg",
          "/rooms/Paradiso/paradiso4.jpg",
        ],
        description:
          "Created by joining two of our flagship 5-bedroom luxury villas, Villa Encanto is purpose-built for life's big moments.",
      },
      {
        name: "Villa Marisol",
        images: [
          "/rooms/Magnifica/Magnifica.png",
          "/rooms/Magnifica/magnifica2.webp",
          "/rooms/Magnifica/magnifica6.jpg",
          "/rooms/Magnifica/magnifica12.webp",
          "/rooms/Magnifica/magnifica8.jpg",
          "/rooms/Magnifica/magnifica14.webp",
          "/rooms/Magnifica/magnifica10.webp",
          "/rooms/Magnifica/magnifica11.jpg",
          "/rooms/Magnifica/magnifica18.jpg",
          "/rooms/Magnifica/magnifica19.webp",
          "/rooms/Paradiso/Paradiso.png",
          "/rooms/Paradiso/paradiso1.jpg",
          "/rooms/Paradiso/paradiso5.jpg",
          "/rooms/Paradiso/paradiso6.webp",
          "/rooms/Paradiso/paradiso10.jpg",
          "/rooms/Paradiso/paradiso11.jpg",
          "/rooms/Paradiso/paradiso12.jpg",
          "/rooms/Paradiso/paradiso15.webp",
          "/rooms/Paradiso/paradiso2.jpg",
          "/rooms/Serenity/Serenity.png",
          "/rooms/Serenity/serenity8.jpg",
          "/rooms/Serenity/serenity9.jpg",
          "/rooms/Serenity/serenity4.jpg",
          "/rooms/Serenity/serenity1.jpg",
          "/rooms/Paradiso/paradiso4.jpg",
          "/rooms/Magnifica/magnifica17.webp",
          "/rooms/Magnifica/magnifica13.webp",
          "/rooms/Magnifica/magnifica4.jpg",
          "/rooms/Magnifica/magnifica1.jpg",
          "/rooms/Magnifica/magnifica5.jpg",
          "/rooms/Magnifica/magnifica9.jpg",
          "/rooms/Magnifica/magnifica15.jpg",
          "/rooms/Magnifica/magnifica16.webp",
          "/rooms/Magnifica/magnifica20.jpg",
          "/rooms/Magnifica/magnifica3.jpg",
          "/rooms/Magnifica/magnifica7.jpg",
          "/rooms/Emerald/Emerald.png",
          "/rooms/Emerald/emerald1.jpg",
          "/rooms/Emerald/emerald6.webp",
          "/rooms/Emerald/emerald2.jpg",
          "/rooms/Emerald/emerald3.jpg",
          "/rooms/Emerald/emerald4.jpg",
          "/rooms/Emerald/emerald5.webp",
          "/rooms/Regal/Regal.png",
          "/rooms/Regal/regal1.jpg",
          "/rooms/Regal/regal2.jpg",
          "/rooms/Regal/regal3.jpg",
          "/rooms/Regal/regal4.jpg",
          "/rooms/Regal/regal5.jpg",
          "/rooms/Regal/regal6.jpg",
          "/rooms/Regal/regal7.jpg",
          "/rooms/Regal/regal8.jpg",
          "/rooms/Regal/regal9.webp",
        ],
        description:
          "The pinnacle of private group luxury in North Goa, Villa Marisol is the ultimate total takeover of our Mandrem collection.",
      },
    ],

    pilerne: [
      {
        name: "Villa Majestic",
        images: [
          "https://lh3.googleusercontent.com/d/1Ae2jINBXsQAt6hlANAf5es4Ly-P_W00u",
          "https://lh3.googleusercontent.com/d/1y57gRQBG5_-3N3OP_uG9pT1YXNM3JSei",
          "https://lh3.googleusercontent.com/d/15cpLYfghLZm_iSd2IOeo4nQLjC8bh_Wy",
          "https://lh3.googleusercontent.com/d/1Z1vuFVVF0L2_4FoZvFHgcUTKSf55fm9a",
          "https://lh3.googleusercontent.com/d/1W_JNK4dv9H1vlQMUW8Qv7ci1IXxJRSBy",
          "https://lh3.googleusercontent.com/d/1fn1z33GXAfKvtjKEi9V5GrvcdXxzV3iV",
          "https://lh3.googleusercontent.com/d/1Ym3OP3_fogqeguOPAx4-ntWGmQKeOJ3q",
          "https://lh3.googleusercontent.com/d/1B0Z44BwYawsoZmQlJX5ZS-ZD40AtPFP6",
          "https://lh3.googleusercontent.com/d/1EAk6jPsBGBbO5kRSUCcW4xrHuHLrxKT5",
          "https://lh3.googleusercontent.com/d/1zsCC6c-LugweL-PngyjnrU2IAY7Du-Wp",
          "https://lh3.googleusercontent.com/d/1-vRXs7AmssYFq8U8A5km8a4Y1FGoAUoV",
          "https://lh3.googleusercontent.com/d/1l3FcDfyAH3jkptvoEE6zZY5TPAUFpfQz",
          "https://lh3.googleusercontent.com/d/1A56wEg0HNinw_c6kGRF1W3z_m3kpxKCp",
          "https://lh3.googleusercontent.com/d/1MkNzdk55_LmVORPqve1ehvLxOYDtNVoC",
          "https://lh3.googleusercontent.com/d/1GK6sTc641VnApTeIjIK62aquly1s5EnZ",
          "https://lh3.googleusercontent.com/d/1wqt19RJKZUjzb8vemcBxiZcuTlYp8dxq",
          "https://lh3.googleusercontent.com/d/1kEXnjOYHFXhJkHMyH4LBRMJuNY6cJFqL",
        ],
        description:
          "Picture this: Greek-inspired elegance meets tropical bliss, all wrapped up in the heart of Goa.",
      },
      {
        name: "Villa Grande",
        images: [
          "https://lh3.googleusercontent.com/d/1_Y5GfRSkWCAQdubo8cHzrVKcW1_0Zdve",
          "https://lh3.googleusercontent.com/d/1Ad9bdJ7TyqE6plj7ySLdDwIV0A6DQ_aM",
          "https://lh3.googleusercontent.com/d/1xg05eqMCot4T0JnWk_YUDGOiOqKdUZb3",
          "https://lh3.googleusercontent.com/d/13FOZuFSG7Jyyg4C4hge8718MQn_wDH_T",
          "https://lh3.googleusercontent.com/d/1USS4apmyYC75KkAAL78YoH-zMXGMF85S",
          "https://lh3.googleusercontent.com/d/10DchjSd-ZD-fvWGwqhoQeh8zfBdRWwk6",
          "https://lh3.googleusercontent.com/d/14m1rp5GI4Fc_6arvwQtufK6NOJWypaXQ",
          "https://lh3.googleusercontent.com/d/1dr89fzOzeQKha64Xl9sbHoCn3j9Uq-re",
          "https://lh3.googleusercontent.com/d/1hZgLABFKAnsMnlbMtZxBFgEQhLf4i7X_",
          "https://lh3.googleusercontent.com/d/1IqDy8W7UapgmNV0BsmxaIO6cdRwFJTXp",
          "https://lh3.googleusercontent.com/d/1uPch8US4k4H1jI-yvChE_g1LsgjE8zWK",
          "https://lh3.googleusercontent.com/d/1T_xUtjhHdfx2znKjd5OOir4Xri9muK5E",
          "https://lh3.googleusercontent.com/d/1RhtvIAa9wWVOTT0-P2nTBiOmdFrXxE_s",
          "https://lh3.googleusercontent.com/d/1oA_Vj3EyD5ao-62yx8ANfEdhO6MDOo_M",
          "https://lh3.googleusercontent.com/d/1kcNzVl8jIvpnCBTuQtQWkZYHGbi-vTA3",
          "https://lh3.googleusercontent.com/d/1x1K54y1c2LJockuEuSQKHlnJZwy2HKNr",
          "https://lh3.googleusercontent.com/d/1i_H6bn1xObc4WHOHXc2uhKNWL3vOGejC",
          "https://lh3.googleusercontent.com/d/1fEvl4j-eAuvhubSwr0dIh9-Ujh94YOAS",
          "https://lh3.googleusercontent.com/d/1y-kx9m2dfaNia7TVRLQCrK5hJe2OMM6d",
          "https://lh3.googleusercontent.com/d/1rMZFTJ5HEaPimeOcNT-5Tk8v7BwXtdOq",
        ],
        description:
          "Welcome to Aroha Palms Grande, Goa's premier luxury art villa rental.",
      },
      {
        name: "Villa Imperial",
        images: [
          "https://lh3.googleusercontent.com/d/1_Y5GfRSkWCAQdubo8cHzrVKcW1_0Zdve",
          "https://lh3.googleusercontent.com/d/1Ae2jINBXsQAt6hlANAf5es4Ly-P_W00u",
          "https://lh3.googleusercontent.com/d/1Ad9bdJ7TyqE6plj7ySLdDwIV0A6DQ_aM",
          "https://lh3.googleusercontent.com/d/1y57gRQBG5_-3N3OP_uG9pT1YXNM3JSei",
          "https://lh3.googleusercontent.com/d/1xg05eqMCot4T0JnWk_YUDGOiOqKdUZb3",
          "https://lh3.googleusercontent.com/d/15cpLYfghLZm_iSd2IOeo4nQLjC8bh_Wy",
          "https://lh3.googleusercontent.com/d/13FOZuFSG7Jyyg4C4hge8718MQn_wDH_T",
          "https://lh3.googleusercontent.com/d/1Z1vuFVVF0L2_4FoZvFHgcUTKSf55fm9a",
          "https://lh3.googleusercontent.com/d/1USS4apmyYC75KkAAL78YoH-zMXGMF85S",
          // "https://lh3.googleusercontent.com/d/1W_JNK4dv9H1vlQMUW8Qv7ci1IXxJRSBy",
          // "https://lh3.googleusercontent.com/d/10DchjSd-ZD-fvWGwqhoQeh8zfBdRWwk6",
          // "https://lh3.googleusercontent.com/d/1fn1z33GXAfKvtjKEi9V5GrvcdXxzV3iV",
          // "https://lh3.googleusercontent.com/d/14m1rp5GI4Fc_6arvwQtufK6NOJWypaXQ",
          // "https://lh3.googleusercontent.com/d/1Ym3OP3_fogqeguOPAx4-ntWGmQKeOJ3q",
          // "https://lh3.googleusercontent.com/d/1dr89fzOzeQKha64Xl9sbHoCn3j9Uq-re",
          // "https://lh3.googleusercontent.com/d/1B0Z44BwYawsoZmQlJX5ZS-ZD40AtPFP6",
          // "https://lh3.googleusercontent.com/d/1hZgLABFKAnsMnlbMtZxBFgEQhLf4i7X_",
          // "https://lh3.googleusercontent.com/d/1EAk6jPsBGBbO5kRSUCcW4xrHuHLrxKT5",
          // "https://lh3.googleusercontent.com/d/1IqDy8W7UapgmNV0BsmxaIO6cdRwFJTXp",
          // "https://lh3.googleusercontent.com/d/1zsCC6c-LugweL-PngyjnrU2IAY7Du-Wp",
          // "https://lh3.googleusercontent.com/d/1uPch8US4k4H1jI-yvChE_g1LsgjE8zWK",
          // "https://lh3.googleusercontent.com/d/1-vRXs7AmssYFq8U8A5km8a4Y1FGoAUoV",
          // "https://lh3.googleusercontent.com/d/1T_xUtjhHdfx2znKjd5OOir4Xri9muK5E",
          // "https://lh3.googleusercontent.com/d/1l3FcDfyAH3jkptvoEE6zZY5TPAUFpfQz",
          // "https://lh3.googleusercontent.com/d/1RhtvIAa9wWVOTT0-P2nTBiOmdFrXxE_s",
          // "https://lh3.googleusercontent.com/d/1A56wEg0HNinw_c6kGRF1W3z_m3kpxKCp",
          // "https://lh3.googleusercontent.com/d/1oA_Vj3EyD5ao-62yx8ANfEdhO6MDOo_M",
          // "https://lh3.googleusercontent.com/d/1MkNzdk55_LmVORPqve1ehvLxOYDtNVoC",
          // "https://lh3.googleusercontent.com/d/1kcNzVl8jIvpnCBTuQtQWkZYHGbi-vTA3",
          // "https://lh3.googleusercontent.com/d/1GK6sTc641VnApTeIjIK62aquly1s5EnZ",
          // "https://lh3.googleusercontent.com/d/1x1K54y1c2LJockuEuSQKHlnJZwy2HKNr",
          "https://lh3.googleusercontent.com/d/1wqt19RJKZUjzb8vemcBxiZcuTlYp8dxq",
          "https://lh3.googleusercontent.com/d/1i_H6bn1xObc4WHOHXc2uhKNWL3vOGejC",
          "https://lh3.googleusercontent.com/d/1kEXnjOYHFXhJkHMyH4LBRMJuNY6cJFqL",
          "https://lh3.googleusercontent.com/d/1fEvl4j-eAuvhubSwr0dIh9-Ujh94YOAS",
          "https://lh3.googleusercontent.com/d/1y-kx9m2dfaNia7TVRLQCrK5hJe2OMM6d",
          "https://lh3.googleusercontent.com/d/1rMZFTJ5HEaPimeOcNT-5Tk8v7BwXtdOq",
        ],
        description:
          "When one villa isn't enough, Villa Imperial opens the door between them — literally.",
      },
    ],
  },

  hero: {
    image: "/images/cover1.jpg",
    title: "Gallery",
    description: `A glimpse of the comfort, beauty, and memories that await.
Every photo tells the story of your perfect stay.`,
  },
};
